// <auto-generated />
using System;
using Korp.Estoque.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Korp.Estoque.Api.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    partial class EstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Korp.Estoque.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PROD001",
                            DataAtualizacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1823),
                            DataCriacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1822),
                            Descricao = "Produto Exemplo 1",
                            Saldo = 100
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PROD002",
                            DataAtualizacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1828),
                            DataCriacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1827),
                            Descricao = "Produto Exemplo 2",
                            Saldo = 50
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PROD003",
                            DataAtualizacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1831),
                            DataCriacao = new DateTime(2025, 12, 6, 3, 32, 36, 530, DateTimeKind.Utc).AddTicks(1831),
                            Descricao = "Produto Exemplo 3",
                            Saldo = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
